### ISSUE TITLE
其他正常，不能播放

### ISSUE THREAD

**Issue by freealong** [zjulmh/doubanFM#1]
Message: PackageKit: Did not install codec: GDBus.Error:org.freedesktop.DBus.Error.UnknownInterface: No such interface 'org.freedesktop.PackageKit.Modify2' at object path '/org/freedesktop/PackageKit'

安装哪个codec？

**Comment by zjulmh** [comment]
请问是哪个操作系统平台？什么Qt版本编译？

**Comment by freealong** [comment]
Fedora21 x86_64;
Qt4.8.6;

**Comment by freealong** [comment]
解决了，缺少gstreamer1-libav
